# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'many_to_one_mapper_dockwidget_base.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_manyToOneMApperDockWidgetBase(object):
    def setupUi(self, manyToOneMApperDockWidgetBase):
        manyToOneMApperDockWidgetBase.setObjectName("manyToOneMApperDockWidgetBase")
        manyToOneMApperDockWidgetBase.resize(658, 655)
        self.dockWidgetContents = QtWidgets.QWidget()
        self.dockWidgetContents.setObjectName("dockWidgetContents")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.dockWidgetContents)
        self.verticalLayout.setObjectName("verticalLayout")
        self.mainWidget = QtWidgets.QWidget(self.dockWidgetContents)
        self.mainWidget.setObjectName("mainWidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.mainWidget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.layerBox1 = QgsMapLayerComboBox(self.mainWidget)
        self.layerBox1.setObjectName("layerBox1")
        self.horizontalLayout_3.addWidget(self.layerBox1)
        self.fieldBox1 = QgsFieldComboBox(self.mainWidget)
        self.fieldBox1.setObjectName("fieldBox1")
        self.horizontalLayout_3.addWidget(self.fieldBox1)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.valueEdit = QtWidgets.QLineEdit(self.mainWidget)
        self.valueEdit.setObjectName("valueEdit")
        self.horizontalLayout.addWidget(self.valueEdit)
        self.goToButton = QtWidgets.QPushButton(self.mainWidget)
        self.goToButton.setObjectName("goToButton")
        self.horizontalLayout.addWidget(self.goToButton)
        self.fromLayerButton = QtWidgets.QPushButton(self.mainWidget)
        self.fromLayerButton.setObjectName("fromLayerButton")
        self.horizontalLayout.addWidget(self.fromLayerButton)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.lastButton = QtWidgets.QPushButton(self.mainWidget)
        self.lastButton.setObjectName("lastButton")
        self.horizontalLayout_4.addWidget(self.lastButton)
        self.featuresBox = featuresWidget(self.mainWidget)
        self.featuresBox.setObjectName("featuresBox")
        self.horizontalLayout_4.addWidget(self.featuresBox)
        self.nextButton = QtWidgets.QPushButton(self.mainWidget)
        self.nextButton.setObjectName("nextButton")
        self.horizontalLayout_4.addWidget(self.nextButton)
        self.verticalLayout_2.addLayout(self.horizontalLayout_4)
        self.view = QtWidgets.QTableView(self.mainWidget)
        self.view.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.view.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.view.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.view.setObjectName("view")
        self.verticalLayout_2.addWidget(self.view)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.layerBox2 = QgsMapLayerComboBox(self.mainWidget)
        self.layerBox2.setObjectName("layerBox2")
        self.horizontalLayout_2.addWidget(self.layerBox2)
        self.fieldBox2 = QgsFieldComboBox(self.mainWidget)
        self.fieldBox2.setObjectName("fieldBox2")
        self.horizontalLayout_2.addWidget(self.fieldBox2)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.verticalLayout.addWidget(self.mainWidget)
        manyToOneMApperDockWidgetBase.setWidget(self.dockWidgetContents)

        self.retranslateUi(manyToOneMApperDockWidgetBase)
        QtCore.QMetaObject.connectSlotsByName(manyToOneMApperDockWidgetBase)

    def retranslateUi(self, manyToOneMApperDockWidgetBase):
        _translate = QtCore.QCoreApplication.translate
        manyToOneMApperDockWidgetBase.setWindowTitle(_translate("manyToOneMApperDockWidgetBase", "Many to One Mapper"))
        self.layerBox1.setToolTip(_translate("manyToOneMApperDockWidgetBase", "<html><head/><body><p>Layer. Many features of join layer are mapped to each feature of this layer.</p></body></html>"))
        self.fieldBox1.setToolTip(_translate("manyToOneMApperDockWidgetBase", "<html><head/><body><p>Target field to add to csv.</p></body></html>"))
        self.valueEdit.setToolTip(_translate("manyToOneMApperDockWidgetBase", "<html><head/><body><p>Target field for current feature of layer.</p></body></html>"))
        self.goToButton.setToolTip(_translate("manyToOneMApperDockWidgetBase", "<html><head/><body><p>Select and zoom to feature of primary layer with this value.</p></body></html>"))
        self.goToButton.setText(_translate("manyToOneMApperDockWidgetBase", "Go To"))
        self.fromLayerButton.setToolTip(_translate("manyToOneMApperDockWidgetBase", "<html><head/><body><p>Set Value from selected feature of layer.</p></body></html>"))
        self.fromLayerButton.setText(_translate("manyToOneMApperDockWidgetBase", "From Layer"))
        self.lastButton.setToolTip(_translate("manyToOneMApperDockWidgetBase", "<html><head/><body><p>Go to last feature</p></body></html>"))
        self.lastButton.setText(_translate("manyToOneMApperDockWidgetBase", "<"))
        self.nextButton.setToolTip(_translate("manyToOneMApperDockWidgetBase", "<html><head/><body><p>Go to next feature</p></body></html>"))
        self.nextButton.setText(_translate("manyToOneMApperDockWidgetBase", ">"))
        self.view.setToolTip(_translate("manyToOneMApperDockWidgetBase", "<html><head/><body><p>id and join field for features of join layer mapped to current feature of layer.</p><p>Right click for options to add and remove.</p><p><br/></p></body></html>"))
        self.layerBox2.setToolTip(_translate("manyToOneMApperDockWidgetBase", "<html><head/><body><p>Join layer.</p></body></html>"))
        self.fieldBox2.setToolTip(_translate("manyToOneMApperDockWidgetBase", "<html><head/><body><p>Join field to add to csv.</p></body></html>"))
from .featuresWidget.featuresWidget import featuresWidget
from qgsfieldcombobox import QgsFieldComboBox
from qgsmaplayercombobox import QgsMapLayerComboBox
